### PR TITLE
ecp5: Add regression tests

### PR DESCRIPTION
**Pull request by daveshah1**
For YosysHQ/nextpnr#191, YosysHQ/nextpnr#194 and YosysHQ/nextpnr#235

At the moment there isn't a ECP5 equivalent to icebox_vlog, but we check the resultant config file can be correctly packed to a bitstream (e.g. checking that it doesn't have any pips that don't exist, or invalid config enum values).

### CODE REVIEW

**Comment by eddiehung** [comment]
Why doesn't CI run for this? I'll take a look tomorrow unless you beat me to it...

**Comment by daveshah1** [comment]
CI isn't set up in this repo, only in nextpnr itself. I've created YosysHQ/nextpnr#244 to run CI.

**Review by eddiehung — APPROVED** [review]
Right you are!
YosysHQ/nextpnr#244 runs clean. Go for merge.

**Comment by eddiehung** [comment]
We still need to figure out a system where there is only one PR (preferably in [YosysHQ/nextpnr](http://github.com/YosysHQ/nextpnr) so we can see it do CI properly).

**Pull request merged**
